import type { DiscoverProfile, Profile, ProfilePhoto, VerificationStatus } from "@/types";

function demoPhotos(profileId: string, urls: string[]): ProfilePhoto[] {
  return urls.map((url, index) => ({
    id: `p-${profileId}-${index}`,
    profile_id: profileId,
    url,
    sort_order: index,
    is_private: false,
    is_primary: index === 0,
    created_at: "",
    updated_at: "",
  }));
}

const ANANYA_PHOTOS = demoPhotos("demo-1", [
  "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=800&h=1000&fit=crop",
  "https://images.unsplash.com/photo-1517841905240-472988babdf9?w=800&h=1000&fit=crop",
  "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=800&h=1000&fit=crop",
  "https://images.unsplash.com/photo-1524504388940-b1c1722653e1?w=800&h=1000&fit=crop",
]);

const VIKRAM_PHOTOS = demoPhotos("demo-2", [
  "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=800&h=1000&fit=crop",
  "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=800&h=1000&fit=crop",
  "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=800&h=1000&fit=crop",
]);

const PRIYA_PHOTOS = demoPhotos("demo-3", [
  "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=800&h=1000&fit=crop",
  "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=800&h=1000&fit=crop",
  "https://images.unsplash.com/photo-1487412720507-e7ab37603c6f?w=800&h=1000&fit=crop",
]);

export const DEMO_PROFILES: DiscoverProfile[] = [
  {
    id: "demo-1",
    user_id: "user-1",
    full_name: "Ananya Rawat",
    gender: "female",
    looking_for: "male",
    dob: "1998-03-15",
    age: 27,
    city: "Dehradun",
    district: "Dehradun",
    village: "Rajpur",
    region: "garhwal",
    education: "Masters in Psychology",
    profession: "Counselor",
    bio: "Rooted in Garhwal, growing in Dehradun. I believe in slow, intentional connections built on trust and shared values.",
    ai_bio: "A thoughtful counselor from Garhwal who values deep conversations and genuine connection.",
    intent: "serious",
    profile_status: "active",
    trust_score: 85,
    compatibility_score: 0,
    readiness_score: 78,
    personality_tags: ["thoughtful", "caring", "grounded"],
    interest_tags: ["trekking", "reading", "yoga"],
    values_tags: ["trust", "communication", "growth"],
    lifestyle: { smoking: "never", drinking: "never", food_preference: "veg", kids_preference: "want", relocation: "open" },
    family_background: { family_type: "nuclear", religious_preference: "spiritual", family_involvement: "moderate" },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    photos: ANANYA_PHOTOS,
    verification: { id: "v1", profile_id: "demo-1", mobile_verified: true, face_verified: true, id_verified: true, family_verified: false, verified_at: new Date().toISOString(), created_at: "", updated_at: "" },
    distance_label: "12 km away",
  },
  {
    id: "demo-2",
    user_id: "user-2",
    full_name: "Vikram Singh",
    gender: "male",
    looking_for: "female",
    dob: "1995-07-22",
    age: 30,
    city: "Nainital",
    district: "Nainital",
    village: "Mukteshwar",
    region: "kumaon",
    education: "B.Tech, IIT Roorkee",
    profession: "Software Engineer",
    bio: "Kumaoni at heart, building products in tech. Looking for someone who values family roots and modern thinking.",
    ai_bio: null,
    intent: "marriage",
    profile_status: "active",
    trust_score: 92,
    compatibility_score: 0,
    readiness_score: 85,
    personality_tags: ["ambitious", "family oriented", "grounded"],
    interest_tags: ["trekking", "photography", "music"],
    values_tags: ["respect", "commitment", "tradition"],
    lifestyle: { smoking: "never", drinking: "occasionally", food_preference: "veg", kids_preference: "want", relocation: "willing" },
    family_background: { family_type: "joint", religious_preference: "hindu", family_involvement: "high" },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    photos: VIKRAM_PHOTOS,
    verification: { id: "v2", profile_id: "demo-2", mobile_verified: true, face_verified: true, id_verified: true, family_verified: true, verified_at: new Date().toISOString(), created_at: "", updated_at: "" },
    distance_label: "45 km away",
  },
  {
    id: "demo-3",
    user_id: "user-3",
    full_name: "Priya Bisht",
    gender: "female",
    looking_for: "male",
    dob: "2000-11-08",
    age: 25,
    city: "Haridwar",
    district: "Haridwar",
    village: "Rishikesh Road",
    region: "garhwal",
    education: "B.Com, Delhi University",
    profession: "Marketing Manager",
    bio: "Exploring life and connections. Love the mountains, good food, and meaningful conversations.",
    ai_bio: null,
    intent: "exploring",
    profile_status: "active",
    trust_score: 72,
    compatibility_score: 0,
    readiness_score: 55,
    personality_tags: ["adventurous", "creative", "warm"],
    interest_tags: ["travel", "cooking", "fitness"],
    values_tags: ["independence", "balance", "trust"],
    lifestyle: { smoking: "never", drinking: "occasionally", food_preference: "veg", kids_preference: "open", relocation: "open" },
    family_background: { family_type: "nuclear", religious_preference: "spiritual" },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    photos: PRIYA_PHOTOS,
    verification: { id: "v3", profile_id: "demo-3", mobile_verified: true, face_verified: true, id_verified: false, family_verified: false, verified_at: null, created_at: "", updated_at: "" },
    distance_label: "28 km away",
  },
];

export const DEMO_CURRENT_PROFILE_PHOTOS = demoPhotos("current-user", [
  "https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=800&q=80",
  "https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&w=800&q=80",
  "https://images.unsplash.com/photo-1524504388940-b1c1722653e1?auto=format&fit=crop&w=800&q=80",
]);

export const DEMO_CURRENT_PROFILE: Profile = {
  id: "current-user",
  user_id: "current",
  full_name: "You",
  gender: "male",
  looking_for: "female",
  dob: "1997-01-01",
  age: 28,
  city: "Dehradun",
  district: "Dehradun",
  village: "Clement Town",
  region: "garhwal",
  education: "MBA",
  profession: "Product Manager",
  bio: "Building meaningful connections in Uttarakhand.",
  ai_bio: "A product-minded professional rooted in Garhwal, seeking genuine connection.",
  intent: "serious",
  profile_status: "active",
  trust_score: 75,
  compatibility_score: 0,
  readiness_score: 70,
  personality_tags: ["thoughtful", "ambitious"],
  interest_tags: ["trekking", "reading"],
  values_tags: ["trust", "communication"],
  lifestyle: { smoking: "never", drinking: "occasionally", food_preference: "veg" },
  family_background: { family_type: "nuclear" },
  created_at: new Date().toISOString(),
  updated_at: new Date().toISOString(),
};

export const DEMO_VERIFICATION: VerificationStatus = {
  id: "v-current",
  profile_id: "current-user",
  mobile_verified: true,
  face_verified: true,
  id_verified: false,
  family_verified: false,
  verified_at: new Date().toISOString(),
  created_at: new Date().toISOString(),
  updated_at: new Date().toISOString(),
};
